package eventsource

import (
	"github.com/golly-go/golly"
	"github.com/stretchr/testify/mock"
)

const (
	mockRepoContextKey golly.ContextKeyT = "es_mock_repo_context_key"
)

// MockRepository is an autogenerated mock type for the Repository type

type MockRepository struct {
	mock.Mock
}

func (m *MockRepository) Load(ctx golly.Context, object interface{}) error {
	args := m.Called(ctx, object)
	return args.Error(0)
}

func (m *MockRepository) Save(ctx golly.Context, object interface{}) error {
	args := m.Called(ctx, object)

	return args.Error(0)
}

func (m *MockRepository) Transaction(ctx golly.Context, fn func(golly.Context, Repository) error) error {
	return fn(ctx, m)
}

func (m *MockRepository) IsNewRecord(obj interface{}) bool {
	args := m.Called(obj)
	return args.Bool(0)
}

func NewTestRepository(ctx golly.Context) (golly.Context, *MockRepository) {
	repo := &MockRepository{}

	ctx = ctx.Set(mockRepoContextKey, repo)

	return ctx, repo
}

func repoFromContext(ctx golly.Context) *MockRepository {
	val, _ := ctx.Get(mockRepoContextKey)

	if val == nil {
		return nil
	}

	return val.(*MockRepository)
}
