name: CI / CD
on:
  push:
    branches: [main]

env:
  GITHUB_REF: ${{ github.ref }}
  IMAGE: ${{ github.event.repository.name }}
  REGISTRY_HOSTNAME: gcr.io/earnest-cooler-381501
  PROJECT_ID: earnest-cooler-381501
  DEPLOYMENT_NAME: zephyrian-web
  PRODUCTION_CLUSTER_NAME: zephyrian-cluster
  PRODUCTION_CLUSTER_ZONE: us-central1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Dirs
        run: make dirs

      - name: Dependencies
        run: make deps

      - name: Vet
        run: make vet

      - name: Test
        run: make tests
